package com.konfigyr.gradle;

import com.konfigyr.ArtifactMetadataResource;
import com.konfigyr.ArtifactMetadataScanner;
import com.konfigyr.artifactory.PropertyDescriptor;
import org.gradle.api.GradleException;
import org.gradle.api.artifacts.transform.*;
import org.gradle.api.file.FileCollection;
import org.gradle.api.file.FileSystemLocation;
import org.gradle.api.logging.Logger;
import org.gradle.api.logging.Logging;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.Classpath;
import org.gradle.api.tasks.CompileClasspath;
import org.gradle.api.tasks.Internal;
import org.jspecify.annotations.NullMarked;

import java.io.File;
import java.util.ArrayList;
import java.util.List;

/**
 * A Gradle {@link TransformAction} that processes each JAR on the {@code runtimeClasspath} and produces
 * a self-describing output file containing the {@link PropertyDescriptor} metadata. This transform
 * action would create a custom {@link ClassLoader} using the current artifact and its dependencies to
 * resolve the Spring Boot configuration metadata files and generate the property descriptors.
 * <p>
 * The resulting artifacts can be looked up using a custom {@link org.gradle.api.artifacts.ArtifactView}
 * where the {@code artifactType} is set to {@code konfigyr-metadata}. Artifacts that do not contain
 * Spring Boot configuration metadata would not be included in the view.
 * <p>
 * The transform is annotated {@link CacheableTransform}. Gradle will cache the output directory keyed
 * on the JAR's content hash. A JAR that has not changed between builds will never be re-processed;
 * the cached output directory is reused directly, making incremental builds extremely fast.
 *
 * @author Vladimir Spasic
 * @since 1.0.0
 */
@NullMarked
@CacheableTransform
public abstract class ArtifactMetadataTransform implements TransformAction<ArtifactMetadataTransform.Parameters> {

    /**
     * The custom artifact type that would be generated by this transform action.
     */
    static final String ARTIFACT_TYPE = "konfigyr-metadata";

    /**
     * The name of the metadata file that would be generated by this transform action.
     */
    static final String METADATA_FILE_NAME = "metadata.json";

    final Logger logger = Logging.getLogger(getClass());

    /**
     * The location of the artifact file being transformed.
     * <p>
     * {@code @Classpath} annotation here tells Gradle to derive the cache key from the artifact's
     * content hash rather than its path, normalizing manifest/timestamp noise while still hashing
     * resource files. This artifact is scanned for {@code META-INF/spring-configuration-metadata.json}
     * resources, so {@code @CompileClasspath} normalization would be incorrect here: it discards
     * non-class resources from the cache key entirely, which would let a dependency's configuration
     * metadata change (e.g. a default value or description) without invalidating this transform's
     * cached output.
     *
     * @return the artifact file, never {@literal null}.
     */
    @InputArtifact
    @Classpath
    public abstract Provider<FileSystemLocation> getArtifact();

    /**
     * The file collection containing the dependencies of the artifact being transformed.
     * <p>
     * This collection is used to create a custom {@link ClassLoader} that can resolve the Java
     * types from the Spring Boot configuration metadata files to resolve the
     * {@link com.konfigyr.artifactory.JsonSchema} for each property.
     *
     * @return the dependencies of the artifact, never {@literal null}.
     */
    @CompileClasspath
    @InputArtifactDependencies
    public abstract FileCollection getDependencies();

    @Override
    public void transform(TransformOutputs outputs) {
        final File artifact = getArtifact().get().getAsFile();

        try {
            // Local project modules expose a class-output directory, not a JAR.
            // The service's own metadata lives here before the jar task runs.
            final List<ArtifactMetadataResource> candidates = ArtifactMetadataScanner.scan(artifact);

            if (candidates.isEmpty()) {
                logger.debug("No Spring Boot configuration metadata files found in artifact: {}", artifact);
                return;
            }

            final File output = outputs.file(METADATA_FILE_NAME);
            final ArtifactoryService service = getParameters().getService().get();

            if (logger.isDebugEnabled()) {
                logger.debug("Generating configuration property descriptors into: {}", output);
            }

            final List<File> classpath = new ArrayList<>(getDependencies().getFiles());
            classpath.add(artifact);

            service.writePropertyDescriptorMetadata(candidates, classpath, output);
        } catch (Exception ex) {
            throw new GradleException("Failed to generate Konfigyr property descriptor metadata for artifact: " +
                    artifact, ex);
        }
    }

    interface Parameters extends TransformParameters {

        @Internal
        Property<ArtifactoryService> getService();

    }

}
