package com.konfigyr.gradle;

import com.konfigyr.artifactory.PropertyDescriptor;
import org.gradle.api.GradleException;
import org.gradle.api.artifacts.transform.*;
import org.gradle.api.file.FileCollection;
import org.gradle.api.file.FileSystemLocation;
import org.gradle.api.logging.Logger;
import org.gradle.api.logging.Logging;
import org.gradle.api.provider.Property;
import org.gradle.api.provider.Provider;
import org.gradle.api.tasks.CompileClasspath;
import org.gradle.api.tasks.Internal;
import org.jspecify.annotations.NullMarked;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.FileSystemResource;
import org.springframework.core.io.Resource;

import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.zip.ZipEntry;
import java.util.zip.ZipFile;

/**
 * A Gradle {@link TransformAction} that processes each JAR on the {@code runtimeClasspath} and produces
 * a self-describing output file containing the {@link PropertyDescriptor} metadata. This transform
 * action would create a custom {@link ClassLoader} using the current artifact and its dependencies to
 * resolve the Spring Boot configuration metadata files and generate the property descriptors.
 * <p>
 * The resulting artifacts can be looked up using a custom {@link org.gradle.api.artifacts.ArtifactView}
 * where the {@code artifactType} is set to {@code konfigyr-metadata}. Artifacts that do not contain
 * Spring Boot configuration metadata would not be included in the view.
 * <p>
 * The transform is annotated {@link CacheableTransform}. Gradle will cache the output directory keyed
 * on the JAR's content hash. A JAR that has not changed between builds will never be re-processed;
 * the cached output directory is reused directly, making incremental builds extremely fast.
 *
 * @author Vladimir Spasic
 * @since 1.0.0
 */
@NullMarked
@CacheableTransform
public abstract class ArtifactMetadataTransform implements TransformAction<ArtifactMetadataTransform.Parameters> {

    /**
     * The custom artifact type that would be generated by this transform action.
     */
    static final String ARTIFACT_TYPE = "konfigyr-metadata";

    /**
     * The name of the metadata file that would be generated by this transform action.
     */
    static final String METADATA_FILE_NAME = "metadata.json";

    static final Set<String> METADATA_PATHS = Set.of(
            "META-INF/spring-configuration-metadata.json",
            "META-INF/additional-spring-configuration-metadata.json",
            "META-INF/spring/org.springframework.boot.configuration-metadata.json"
    );

    final Logger logger = Logging.getLogger(getClass());

    /**
     * The location of the artifact file being transformed.
     * <p>
     * {@code @Classpath} annotation here tells Gradle to derive the cache key from the artifacts
     * content hash rather than its path. This is essential for correctness in reproducible and
     * relocatable builds.
     *
     * @return the artifact file, never {@literal null}.
     */
    @InputArtifact
    @CompileClasspath
    public abstract Provider<FileSystemLocation> getArtifact();

    /**
     * The file collection containing the dependencies of the artifact being transformed.
     * <p>
     * This collection is used to create a custom {@link ClassLoader} that can resolve the Java
     * types from the Spring Boot configuration metadata files to resolve the
     * {@link com.konfigyr.artifactory.JsonSchema} for each property.
     *
     * @return the dependencies of the artifact, never {@literal null}.
     */
    @CompileClasspath
    @InputArtifactDependencies
    public abstract FileCollection getDependencies();

    @Override
    public void transform(TransformOutputs outputs) {
        final File artifact = getArtifact().get().getAsFile();

        if (!artifact.exists()) {
            return;
        }

        final List<Resource> candidates;

        try {
            // Local project modules expose a class-output directory, not a JAR.
            // The service's own metadata lives here before the jar task runs.
            if (artifact.isDirectory()) {
                candidates = processDirectory(artifact);
            } else {
                candidates = processJar(artifact);
            }

            if (candidates.isEmpty()) {
                logger.debug("No Spring Boot configuration metadata files found in artifact: {}", artifact);
                return;
            }

            final File output = outputs.file(METADATA_FILE_NAME);
            final ArtifactoryService service = getParameters().getService().get();

            if (logger.isDebugEnabled()) {
                logger.debug("Generating configuration property descriptors into: {}", output);
            }

            final List<File> classpath = new ArrayList<>(getDependencies().getFiles());
            classpath.add(artifact);

            service.writePropertyDescriptorMetadata(candidates, classpath, output);
        } catch (Exception ex) {
            throw new GradleException("Failed to generate Konfigyr property descriptor metadata for artifact: " +
                    artifact, ex);
        }
    }

    private List<Resource> processJar(File jar) throws IOException {
        final List<Resource> candidates = new ArrayList<>();

        try (var zip = new ZipFile(jar)) {
            for (String path : METADATA_PATHS) {
                final ZipEntry entry = zip.getEntry(path);
                if (entry != null) {
                    if (logger.isDebugEnabled()) {
                        logger.debug("Found configuration metadata file '{}' in Artifact JAR: {}", path, jar.getName());
                    }

                    final InputStream is = zip.getInputStream(entry);
                    candidates.add(new ByteArrayResource(is.readAllBytes(), entry.getName()));
                }
            }
        }

        return candidates;
    }

    private List<Resource> processDirectory(File dir) {
        final List<Resource> candidates = new ArrayList<>();

        for (String path : METADATA_PATHS) {
            final File metadata = new File(dir, path);

            if (metadata.exists()) {
                if (logger.isDebugEnabled()) {
                    logger.debug("Found configuration metadata file '{}' in project: {}", path, dir.getName());
                }

                candidates.add(new FileSystemResource(metadata));
            }
        }

        return candidates;
    }

    interface Parameters extends TransformParameters {

        @Internal
        Property<ArtifactoryService> getService();

    }

}
