package com.konfigyr.gradle;

import com.konfigyr.HttpResponseException;
import com.konfigyr.artifactory.ArtifactMetadata;
import org.gradle.api.DefaultTask;
import org.gradle.api.file.RegularFileProperty;
import org.gradle.api.provider.Property;
import org.gradle.api.tasks.*;
import org.gradle.work.DisableCachingByDefault;
import org.jspecify.annotations.NonNull;

import java.io.File;
import java.time.Duration;

/**
 * Task that publishes this project's own {@link ArtifactMetadata}, generated by
 * {@link GenerateArtifactMetadataTask}, directly to the Konfigyr Artifactory.
 * <p>
 * If this project's own jar does not expose Spring Boot configuration metadata, this task has
 * nothing to publish and does nothing. Publishing requires the namespace holding this project's
 * {@code groupId} to be verified by the Konfigyr Artifactory — if it isn't, the underlying call
 * fails with an {@link HttpResponseException}, which this task lets propagate rather than
 * special-casing.
 *
 * @author Vladimir Spasic
 * @since 1.0.0
 */
@DisableCachingByDefault(because = "Performs a network call against a stateful remote service")
public abstract class PublishArtifactMetadataTask extends DefaultTask {

    /**
     * The name of the task to be registered in the Gradle build.
     */
    static final String NAME = "publishArtifactMetadata";

    /**
     * Returns the {@link ArtifactoryService} to use for publishing the artifact metadata.
     *
     * @return the artifactory service to use, never {@literal null}.
     */
    @Internal
    public abstract Property<ArtifactoryService> getService();

    /**
     * The file containing this project's own serialized {@link ArtifactMetadata}, written by
     * {@link GenerateArtifactMetadataTask}. The file itself may not exist if this project's own jar
     * does not expose Spring Boot configuration metadata, in which case this task does nothing.
     * <p>
     * It is declared as {@link Internal} rather than {@code @InputFile}, since Gradle's input validation
     * requires an {@code @InputFile} to exist whenever its property has a value, even if marked
     * {@code @Optional}; this task is already {@link DisableCachingByDefault} and never eligible for
     * up-to-date checks, so nothing is lost by not tracking it as a cacheable input.
     *
     * @return the artifact metadata file location, never {@literal null}.
     */
    @Internal
    public abstract RegularFileProperty getMetadata();

    /**
     * The maximum time in milliseconds to wait for a successful poll of a release.
     *
     * @return the release timeout, never {@literal null}.
     * @see com.konfigyr.gradle.KonfigyrExtension.PublishSpec#getPollTimeout()
     */
    @Input
    public abstract Property<@NonNull Duration> getReleaseTimeout();

    /**
     * The initial time interval in milliseconds between consecutive polling attempts to check for a release.
     *
     * @return the release polling interval, never {@literal null}.
     * @see com.konfigyr.gradle.KonfigyrExtension.PublishSpec#getPollInterval()
     */
    @Input
    public abstract Property<@NonNull Duration> getReleasePollingInterval();

    @TaskAction
    void publishArtifactMetadata() {
        final File metadataFile = getMetadata().get().getAsFile();

        if (!metadataFile.exists()) {
            getLogger().debug("No artifact metadata produced by this project, nothing to publish to Artifactory");
            return;
        }

        final ArtifactoryService service = getService().get();
        final ArtifactMetadata metadata = service.readArtifactMetadata(metadataFile);

        service.publish(metadata, getReleaseTimeout().get(), getReleasePollingInterval().get());
    }

}
