name: Pull Request check

permissions:
  contents: read
  checks: write
  pull-requests: write

on:
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v6
        with:
          cache-read-only: true

      - name: Build
        run: ./gradlew --no-daemon --no-parallel --continue check

      - name: Test Reports
        uses: mikepenz/action-junit-report@v6
        if: success() || failure()
        with:
          report_paths: '**/build/test-results/test/TEST-*.xml'

      - name: Test coverage reports
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
